server {
    listen 80;
    server_name aivideo.hbcjwl.com;
    root /opt/open-ai-canvas/web;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
